### ISSUE TITLE
One modification please to pytest_django_haystack?

### ISSUE THREAD

**Issue by cclauss** [rouge8/dotfiles#7]
Sorry to bug you on an archived repo but [`request.getfuncargvalue('db')` in __pytest-django-haystack__](https://github.com/rouge8/pytest-django-haystack/blob/master/pytest_django_haystack.py#L30) is causing me no end of grief on a project.

I know that https://github.com/rouge8/pytest-django-haystack is archived but would you be willing to push a change up to PyPI?
```python
-        request.getfuncargvalue('db')

+        try:  # pytest < v4
+            request.getfuncargvalue('db')
+        except AttributeError:  # pytest >= v4
+            request.getfixturevalue('db')
```
I have tried pulling `pytest_django_haystack.py` into my project but then I cannot figure out how to [make pytest recognize it as a pytest plugin](https://github.com/rouge8/pytest-django-haystack/blob/master/setup.py#L40-L41).

If this is an unreasonable request, then any pointers for how to test `django-haystack` would be appreciated.

**Comment by rouge8** [comment]
You can specify `pytest_plugins` in `conftest.py`: https://docs.pytest.org/en/latest/how-to/plugins.html#requiring-loading-plugins-in-a-test-module-or-conftest-file
